services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
    networks:
      - network1
 
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    networks:
      - network1
  redis:
    image: redis:8.2.3
    container_name: redis_datenbank # <--- Das ist der DNS-Name im Netzwerk!
    ports:
      - "6379:6379"
    networks:
      - network1

  fastapi:
    image: new_rag
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - network1
    depends_on:
      - memgraph
      - redis
    environment: 
      - REDIS_HOST=redis_datenbank  # WICHTIG: Hostname statt localhost
    command: fastapi dev redis_func.py --host 0.0.0.0
    
  arq_worker_get_events:
    image: new_rag
    container_name: arq_worker_give_events
    networks:
      - network1
    depends_on:
      - memgraph
      - redis
    environment: 
      - MEMGRAPH=memgraph
      - REDIS_HOST=redis_datenbank  
    command: arq redis_worker.give_events

  arq-worker:
    image: new_rag
    container_name: arq_worker_get_events
    # Der Worker braucht Redis, um Jobs zu empfangen
    depends_on:
      - redis
    # WICHTIG: Zugriff auf den Docker-Daemon des Hosts, um Browser-Container zu starten (Sibling-Container)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Optional: Mountet den aktuellen Ordner für Live-Code-Changes (nützlich bei Entwicklung mit --watch)
    networks:
      - network1
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # Damit das Python-Skript weiß, wie der Browser-Container heißen soll und in welches Netz er muss
      - DOCKER_CONTAINER_NAME=kernel_browser_arq
      - NETWORK_NAME=allezusammen
      # Redis Konfiguration für ARQ (muss in deiner WorkerSettings Klasse genutzt werden)
      - REDIS_HOST=redis_datenbank
      - REDIS_PORT=6379
      - MEMGRAPH=memgraph
    # Start-Befehl für den Worker. 
    # "dein_worker_modul.WorkerSettings" muss auf die Datei/Klasse zeigen, in der deine WorkerSettings definiert sind.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: arq redis_worker.WorkerSettings 

  frontend:
    image: schulprojekt_frontend_final
    container_name: frontend
    networks:
      - network1
    ports:
      - "4000:3000"

    
networks:
  network1:
    name: allezusammen
    external: true