[project]
name = "new-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.9.4",
    "kernel>=0.17.0",
    "llama-index>=0.14.3",
]
